package rules
import com.example.demo.model.Message
import com.example.demo.model.DoctorAlarm
import com.example.demo.model.AlarmTriggering
import com.example.demo.model.enums.AlarmRisk
import com.example.demo.service.DoctorAlarmService
import com.example.demo.service.AlarmTriggeringService

global DoctorAlarmService alarmService
global AlarmTriggeringService alarmTriggeringService


rule "Low oxygen level and low pressure"
	agenda-group "doctor-alarms"
	
    when
    	Message($oxygenLevel: oxygenLevel, $pressure: pressure, $patient: patient)
    	Number(doubleValue > $oxygenLevel) from accumulate(
    		DoctorAlarm(minOxygenLevel != null, $minOxygenLevel: minOxygenLevel) from alarmService.findAll($patient.getId()),
    		max($minOxygenLevel)
    	)
    	Number(doubleValue > $pressure) from accumulate(
    		DoctorAlarm(minPressure != null, $minPressure: minPressure) from alarmService.findAll($patient.getId()),
    		max($minPressure)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.EXTREME, $patient, 
        	"Oxygen level fell bellow " + $oxygenLevel + " and pressure fell bellow " + $pressure + "!!"));

end

rule "Low pressure and low pulse"
	agenda-group "doctor-alarms"
	
    when
    	Message($pressure: pressure, $pulse: pulse, $patient: patient)
    	Number(doubleValue > $pressure) from accumulate(
    		DoctorAlarm(minPressure != null, $minPressure: minPressure) from alarmService.findAll($patient.getId()),
    		max($minPressure)
    	)
    	Number(doubleValue > $pulse) from accumulate(
    		DoctorAlarm(minPulse != null, $minPulse: minPulse) from alarmService.findAll($patient.getId()),
    		max($minPulse)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.EXTREME, $patient,
        	"Pressure fell bellow " + $pressure + " and pulse fell bellow " + $pulse + "!!"));

end

rule "High pressure and high pulse"
	agenda-group "doctor-alarms"
	
    when
    	Message($pressure: pressure, $pulse: pulse, $patient: patient)
    	Number(doubleValue < $pressure) from accumulate(
    		DoctorAlarm(maxPressure != null, $maxPressure: maxPressure) from alarmService.findAll($patient.getId()),
    		min($maxPressure)
    	)
    	Number(doubleValue < $pulse) from accumulate(
    		DoctorAlarm(maxPulse != null, $maxPulse: maxPulse) from alarmService.findAll($patient.getId()),
    		min($maxPulse)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.EXTREME, $patient,
        	"Pressure has reached " + $pressure + " and pulse has reached " + $pulse + "!!"));

end

rule "Low temperature and low pressure"
	agenda-group "doctor-alarms"
	
    when
    	Message($temperature: temperature, $pressure: pressure, $patient: patient)
    	Number(doubleValue > $temperature) from accumulate(
    		DoctorAlarm(minTemperature != null, $minTemperature: minTemperature) from alarmService.findAll($patient.getId()),
    		max($minTemperature)
    	)
    	Number(doubleValue > $pressure) from accumulate(
    		DoctorAlarm(minPressure != null, $minPressure: minPressure) from alarmService.findAll($patient.getId()),
    		max($minPressure)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.EXTREME, $patient, 
        	"Temperature fell bellow " + $temperature + " and pressure fell bellow " + $pressure + "!!"));

end

rule "High pulse"
	agenda-group "doctor-alarms"
	
    when
    	Message($pulse: pulse, $patient: patient)
    	Number(doubleValue < $pulse) from accumulate(
    		DoctorAlarm(maxPulse != null, $maxPulse: maxPulse) from alarmService.findAll($patient.getId()),
    		min($maxPulse)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Pulse has reached " + $pulse + "!!"));

end

rule "Low pulse"
	agenda-group "doctor-alarms"

    when
    	Message($pulse: pulse, $patient: patient)
    	Number(doubleValue > $pulse) from accumulate(
    		DoctorAlarm(minPulse != null, $minPulse: minPulse) from alarmService.findAll($patient.getId()),
    		max($minPulse)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Pulse fell bellow " + $pulse + "!!"));

end

rule "High pressure"
	agenda-group "doctor-alarms"

    when
    	Message($pressure: pressure, $patient: patient)
    	Number(doubleValue < $pressure) from accumulate(
    		DoctorAlarm(maxPressure != null, $maxPressure: maxPressure) from alarmService.findAll($patient.getId()),
    		min($maxPressure)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Pressure has reached " + $pressure + "!!"));

end

rule "Low pressure"
	agenda-group "doctor-alarms"

    when
    	Message($pressure: pressure, $patient: patient)
    	Number(doubleValue > $pressure) from accumulate(
    		DoctorAlarm(minPressure != null, $minPressure: minPressure) from alarmService.findAll($patient.getId()),
    		max($minPressure)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Pressure fell bellow " + $pressure + "!!"));

end

rule "High temperature"
	agenda-group "doctor-alarms"

    when
    	Message($temperature: temperature, $patient: patient)
    	Number(doubleValue < $temperature) from accumulate(
    		DoctorAlarm(maxTemperature != null, $maxTemperature: maxTemperature) from alarmService.findAll($patient.getId()),
    		min($maxTemperature)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Temperature has reached " + $temperature + "!!"));

end

rule "Low temperature"
	agenda-group "doctor-alarms"

    when
    	Message($temperature: temperature, $patient: patient)
    	Number(doubleValue > $temperature) from accumulate(
    		DoctorAlarm(minTemperature != null, $minTemperature: minTemperature) from alarmService.findAll($patient.getId()),
    		max($minTemperature)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.HIGH, $patient, "Temperature fell bellow " + $temperature + "!!"));

end

rule "High oxygen level"
	agenda-group "doctor-alarms"

    when
    	Message($oxygenLevel: oxygenLevel, $patient: patient)
    	Number(doubleValue < $oxygenLevel) from accumulate(
    		DoctorAlarm(maxOxygenLevel != null, $maxOxygenLevel: maxOxygenLevel) from alarmService.findAll($patient.getId()),
    		min($maxOxygenLevel)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.MODERATE, $patient, "Oxygen level has reached " + $oxygenLevel + "!!"));

end

rule "Low oxygen level"
	agenda-group "doctor-alarms"

    when
    	Message($oxygenLevel: oxygenLevel, $patient: patient)
    	Number(doubleValue > $oxygenLevel) from accumulate(
    		DoctorAlarm(minOxygenLevel != null, $minOxygenLevel: minOxygenLevel) from alarmService.findAll($patient.getId()),
    		max($minOxygenLevel)
    	)
    then
        alarmTriggeringService.save(new AlarmTriggering(AlarmRisk.MODERATE, $patient, "Oxygen level fell bellow " + $oxygenLevel + "!!"));

end